### ISSUE TITLE
Add `required: true` for appropriate inputs in inspec.yml

### ISSUE THREAD

**Issue by karikarshivani** [mitre/microsoft-windows-10-stig-baseline#14]

**Comment by Amndeep7** [comment]
Seems to have been implemented.  Please reopen if necessary @karikarshivani

**Comment by karikarshivani** [comment]
It hasn't been implemented yet so I'm reopening the issue to work on it during the next maintenance phase. Example snippet of the implementation:
```
  - name: administrators
    type: Array
    description: "List of authorized users in the local Administrators group"
    sensitive: true
    required: true
    value:
      -
```
