### ISSUE TITLE
C Folder Default Permissions Mismatch V-63373 (V3R2 - SV-220717)

### ISSUE THREAD

**Issue by njohnson11** [mitre/microsoft-windows-10-stig-baseline#22]
The permissions list set in the inspec.yml file for default C:\ folder permissions does not match the default as described in the control check text. The error occurs in the NT AUTHORITY\Authenticated Users:(S,AD) permission

Check Text
```
c:\\  
    BUILTIN\\Administrators:(OI)(CI)(F)  
    BUILTIN\\Users:(OI)(CI)(RX)  
    NT AUTHORITY\\Authenticated Users:(AD)  
    NT AUTHORITY\\Authenticated Users:(OI)(CI)(IO)(M)  
    NT AUTHORITY\\SYSTEM:(OI)(CI)(F)  
    Mandatory Label\\High Mandatory Level:(OI)(NP)(IO)(NW)
```

Inspec.yml
```
 - name: c_folder_permissions  
    desc: "Default Permissions for C:\\ Folder on OS"  
    type: Array  
    value:  
      - NT AUTHORITY\Authenticated Users:(S,AD)  
      - NT AUTHORITY\Authenticated Users:(OI)(CI)(IO)(M)  
      - NT AUTHORITY\SYSTEM:(OI)(CI)(F)  
      - BUILTIN\Administrators:(OI)(CI)(F)  
      - BUILTIN\Users:(OI)(CI)(RX)  
      - Mandatory Label\High Mandatory Level:(OI)(NP)(IO)(NW)
```
